# Basic
title: 藏心阁
subtitle: 淡然心寄水云间
# welcome_message: <a href="https://github.com/onevcat/vno-jekyll" target="_blank">Download the theme</a>
description: 个人的足迹在这些心的篇章中留下痕迹.
creator: xiaqibin

url: "http://xiaqibin.me"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: green

# The blog button should not be removed.
blog_button:
    title: 个人博客
    description: 个人心藏

# Navigation buttons in the front page.
nav:
    - {title: 学术研究, description: Research Center, url: 'http://drxia.gitee.io'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    # disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    weibo: 木木彡zero
    github: xiaqibin
    twitter: xiaqibin
    # gplus: 107108267983477358170
    mail: xiaqibin01@gmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
